name: GitHub Actions Demo Bootcamp CICD
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
env:
    DUMMY: cicdvar2
jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        DUMMY: cicdvar3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{vars.DUMMY}} ${{ env.DUMMY }}" 